# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  # <<: *default
  # database: building_development
  # username: postgres
  # password: 998915309764

  adapter:  postgresql
  encoding: unicode
  database: railway
  host: postgres.railway.internal
  username: postgres
  port: 56155
  password: IQeMfrkYhWPRDMORQFsyWhgtwqOMaDjR
  url: postgresql://postgres:IQeMfrkYhWPRDMORQFsyWhgtwqOMaDjR@junction.proxy.rlwy.net:56155/railway
  pool: 100


test:
  <<: *default
  database: building_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  adapter:  postgresql
  encoding: unicode
  database: <%= ENV["PGDATABASE"] %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV["PGUSER"] %>
  port: <%= ENV["PGPORT"] %>
  password: <%= ENV["PGPASSWORD"] %>
  url: <%= ENV["DATABASE_PUBLIC_URL"] %>
  pool: 100
